/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqsQueueMessage;

import static sqsQueueMessage.Receive.receive;
import static sqsQueueMessage.Send.send;

public class App {

    public static void main(String[] args) {
        // 100% thanks to Nick Paro for help on this
        String queueName = "";
        switch (args[0]) {
            case "1":
                queueName = "queueA";
                break;
            case "2":
                queueName = "queueB";
                break;
            case "3":
                queueName = "queueC";
                break;
        }
        send(queueName);
        receive(queueName);
    }
}
